export const mockUsers = [
  {
    id: 'u-demo',
    name: 'Demo Student',
    email: 'student@campus.edu.et',
    password: 'password123',
    role: ['student', 'tutor'],
    university: 'Campus University',
    department: 'General Studies',
    year: 'sophomore',
    bio: 'Demo account used to walk through the CampusHustle flow.',
    skillsTeaching: [],
    skillsLearning: ['Python'],
    rating: { knowledge: 0, communication: 0, punctuality: 0, count: 0 },
    verified: true,
    isBlocked: false,
    hourlyRate: null,
    profilePicUrl: '',
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'u-sarah',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@mit.edu.et',
    password: 'Hustle2026!',
    role: ['student', 'tutor'],
    university: 'MIT',
    department: 'Computer Science',
    year: 'senior',
    bio: 'CS senior who loves teaching Python, data structures, and algorithms. Previously interned at a robotics lab and tutored 40+ underclassmen.',
    skillsTeaching: ['Python', 'Data Structures', 'Algorithms'],
    skillsLearning: ['Machine Learning'],
    rating: { knowledge: 4.9, communication: 4.8, punctuality: 5.0, count: 38 },
    verified: true,
    isBlocked: false,
    hourlyRate: 45,
    profilePicUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCslQHgyweBuz6L6u4U7sX-CkO1bMxzKN-rQBsnCRSw0NFuBiUREFnqXGN0EHWLOkQH1mlmYFM_kzXGdcCLDXWU3UU03opJjSut9wuF8XDFLPRDe8NFuHSJ-B8FqAjQsDO-rbuMLwiHmr95Tm8D6VO4w7tYehufIbdQ9QcKPRKHCO2b5bXu6L0mGSef840BdjwW4SQ89f8Qzci3hTGP3lpyuPZhFxS-HCmG73rtnFddDrZQelA_fc01Ew',
    createdAt: '2026-07-28T10:12:00Z',
  },
  {
    id: 'u-david',
    name: 'David Miller',
    email: 'david.miller@stanford.edu.et',
    password: 'Hustle2026!',
    role: ['student', 'tutor'],
    university: 'Stanford',
    department: 'Mathematics',
    year: 'junior',
    bio: 'Math tutor focused on making calculus and linear algebra click. Patient, step-by-step explanations with real practice problems.',
    skillsTeaching: ['Calculus I-III', 'Linear Algebra'],
    skillsLearning: ['Statistics'],
    rating: { knowledge: 4.7, communication: 4.6, punctuality: 4.9, count: 21 },
    verified: true,
    isBlocked: false,
    hourlyRate: 35,
    profilePicUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDjuiqrfilEeL0geLQuIzr7RWq1e6g0TWxPf4vc7tVQPoXyRwipAfp5itd9xN68OFCZ-cY27AZcDhjMOgplRwJ0yZBnpeY28S-C0L5jvjVdFPQoIxdsIt1pF0JbcCpb9AkNYnJzyztbq7VzFRmzeslJOJXUcO8Zh9qHJFLbjqbO4T4wOVHarQRLe5GvIeTLVEkPCXeLpExYT_h_xorEbKPBO6w6ifRU-CL3VszkXoUe-2J88QV6ZZsZVg',
    createdAt: '2026-07-30T14:45:00Z',
  },
  {
    id: 'u-elena',
    name: 'Elena Rodriguez',
    email: 'elena.rodriguez@caltech.edu.et',
    password: 'Hustle2026!',
    role: ['student', 'tutor'],
    university: 'Caltech',
    department: 'Physics',
    year: 'senior',
    bio: 'Physics tutor covering mechanics, electromagnetism, and intro quantum. Great at breaking down problem sets into digestible steps.',
    skillsTeaching: ['Mechanics', 'E&M', 'Quantum'],
    skillsLearning: ['Astrophysics'],
    rating: { knowledge: 5.0, communication: 5.0, punctuality: 4.9, count: 12 },
    verified: true,
    isBlocked: false,
    hourlyRate: 55,
    profilePicUrl:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuALX1qFWj6BQOS-_Oc1QOjMH4vks5Smfenvbp1qmRE43E4dYc-xmGLOLkaumk3HYgMVwMCpDyGYww3ysT7t7SPO2qS-YxCmZ9dD6k-a9F2oOpuDnqp8-sjhBBcE-81yoatFJ294A4BV9qnIXC9DA9MPQ9zK-l9eqNkEIE6oyDGv1WZ9Zqyez1DeduMWcdqYgC-3hFjsKHUSwzeH69co-UZ2B49o2kqzoNT3lYK0IWDODttkaN5CA5NxQQ',
    createdAt: '2026-08-02T08:20:00Z',
  },
  {
    id: 'u-marcus',
    name: 'Marcus Chen',
    email: 'marcus.chen@berkeley.edu.et',
    password: 'Hustle2026!',
    role: ['student', 'tutor'],
    university: 'UC Berkeley',
    department: 'Data Science',
    year: 'junior',
    bio: 'Data science nerd who tutors Python, pandas, and machine learning fundamentals. Portfolio of Kaggle projects to walk through.',
    skillsTeaching: ['Python', 'Machine Learning', 'Data Analysis'],
    skillsLearning: ['Deep Learning'],
    rating: { knowledge: 4.8, communication: 4.7, punctuality: 4.8, count: 27 },
    verified: true,
    isBlocked: false,
    hourlyRate: 40,
    profilePicUrl: '',
    createdAt: '2026-07-29T11:05:00Z',
  },
  {
    id: 'u-aisha',
    name: 'Aisha Patel',
    email: 'aisha.patel@jhu.edu.et',
    password: 'Hustle2026!',
    role: ['student', 'tutor'],
    university: 'Johns Hopkins',
    department: 'Biology',
    year: 'senior',
    bio: 'Pre-med biology tutor for genetics, anatomy, and organic chemistry basics. Friendly and exam-focused study sessions.',
    skillsTeaching: ['Genetics', 'Anatomy', 'Organic Chemistry'],
    skillsLearning: ['MCAT Prep'],
    rating: { knowledge: 4.6, communication: 4.5, punctuality: 4.7, count: 18 },
    verified: true,
    isBlocked: false,
    hourlyRate: 30,
    profilePicUrl: '',
    createdAt: '2026-08-03T16:30:00Z',
  },
  {
    id: 'u-liam',
    name: 'Liam O’Brien',
    email: 'liam.obrien@nyu.edu.et',
    password: 'Hustle2026!',
    role: ['student', 'tutor'],
    university: 'NYU',
    department: 'Economics',
    year: 'senior',
    bio: 'Economics tutor for micro/macro, econometrics, and Excel modeling. Former TA, great at connecting theory to real examples.',
    skillsTeaching: ['Microeconomics', 'Macroeconomics', 'Econometrics'],
    skillsLearning: ['Finance'],
    rating: { knowledge: 4.9, communication: 4.8, punctuality: 4.9, count: 33 },
    verified: true,
    isBlocked: false,
    hourlyRate: 50,
    profilePicUrl: '',
    createdAt: '2026-07-27T13:40:00Z',
  },
  {
    id: 'u-sofia',
    name: 'Sofia Alvarez',
    email: 'sofia.alvarez@columbia.edu.et',
    password: 'Hustle2026!',
    role: ['student', 'tutor'],
    university: 'Columbia',
    department: 'English',
    year: 'junior',
    bio: 'Essay writing and literature tutor. Helps with structure, argumentation, and editing essays across humanities courses.',
    skillsTeaching: ['Essay Writing', 'Literature', 'Editing'],
    skillsLearning: ['Creative Writing'],
    rating: { knowledge: 4.5, communication: 4.6, punctuality: 4.8, count: 15 },
    verified: true,
    isBlocked: false,
    hourlyRate: 25,
    profilePicUrl: '',
    createdAt: '2026-08-04T09:50:00Z',
  },
  {
    id: 'u-daniel',
    name: 'Daniel Kim',
    email: 'daniel.kim@caltech.edu.et',
    password: 'Hustle2026!',
    role: ['student', 'tutor'],
    university: 'Caltech',
    department: 'Chemistry',
    year: 'sophomore',
    bio: 'Chemistry tutor for general and organic chemistry. Loves whiteboard sessions and building problem-solving muscle.',
    skillsTeaching: ['General Chemistry', 'Organic Chemistry'],
    skillsLearning: ['Biochemistry'],
    rating: { knowledge: 4.7, communication: 4.6, punctuality: 4.7, count: 9 },
    verified: true,
    isBlocked: false,
    hourlyRate: 38,
    profilePicUrl: '',
    createdAt: '2026-08-05T15:10:00Z',
  },
]

export const tutors = mockUsers.filter(
  (user) => user.role.includes('tutor') && user.skillsTeaching.length > 0,
)
