// Mock Dataset for CampusHustle Academic Marketplace Admin Dashboard

export const INITIAL_KPIS = [
  {
    id: 'kpi-active-users',
    title: 'Active Users',
    value: '4,892',
    change: '+12.4%',
    isPositive: true,
    timeframe: 'vs last month',
    subtext: '3,840 students active today',
  },
  {
    id: 'kpi-pending-verifications',
    title: 'Pending Verifications',
    value: '48',
    change: '+8.1%',
    isPositive: false,
    timeframe: 'requires action',
    subtext: 'Avg response time: 2.4 hrs',
  },
  {
    id: 'kpi-open-reports',
    title: 'Open Reports',
    value: '19',
    change: '-15.2%',
    isPositive: true,
    timeframe: 'vs last week',
    subtext: '4 High severity tickets',
  },
  {
    id: 'kpi-total-volume',
    title: 'Total Volume',
    value: 'ETB 8,142,450',
    change: '+23.8%',
    isPositive: true,
    timeframe: 'vs last month',
    subtext: 'Processed via Telebirr & CBE',
  },
  {
    id: 'kpi-daily-hustles',
    title: 'Daily Hustles',
    value: '342',
    change: '+18.2%',
    isPositive: true,
    timeframe: 'past 24 hours',
    subtext: 'Tutor sessions & book sales',
  },
]

export const REVENUE_TRENDS_DATA = {
  '7d': [
    { label: 'Mon', revenue: 1420, volume: 38, activeUsers: 840 },
    { label: 'Tue', revenue: 1850, volume: 46, activeUsers: 920 },
    { label: 'Wed', revenue: 2100, volume: 52, activeUsers: 1100 },
    { label: 'Thu', revenue: 1980, volume: 48, activeUsers: 1050 },
    { label: 'Fri', revenue: 2450, volume: 64, activeUsers: 1350 },
    { label: 'Sat', revenue: 3100, volume: 82, activeUsers: 1680 },
    { label: 'Sun', revenue: 2890, volume: 74, activeUsers: 1420 },
  ],
  '30d': [
    { label: 'Week 1', revenue: 12400, volume: 310, activeUsers: 3200 },
    { label: 'Week 2', revenue: 15800, volume: 395, activeUsers: 3850 },
    { label: 'Week 3', revenue: 18200, volume: 440, activeUsers: 4200 },
    { label: 'Week 4', revenue: 21500, volume: 520, activeUsers: 4892 },
  ],
  '1y': [
    { label: 'Jan', revenue: 38000, volume: 920, activeUsers: 2100 },
    { label: 'Feb', revenue: 42500, volume: 1050, activeUsers: 2450 },
    { label: 'Mar', revenue: 51000, volume: 1280, activeUsers: 2900 },
    { label: 'Apr', revenue: 58000, volume: 1420, activeUsers: 3300 },
    { label: 'May', revenue: 64000, volume: 1600, activeUsers: 3750 },
    { label: 'Jun', revenue: 72000, volume: 1850, activeUsers: 4100 },
    { label: 'Jul', revenue: 89000, volume: 2200, activeUsers: 4450 },
    { label: 'Aug', revenue: 105000, volume: 2600, activeUsers: 4892 },
  ],
}

export const CAMPUS_DISTRIBUTION = [
  { campus: 'AAU 4k Main', users: 1420, percentage: 29, activeHustles: 145 },
  { campus: 'ASTU Adama', users: 980, percentage: 20, activeHustles: 88 },
  { campus: 'Hawassa Univ', users: 750, percentage: 15, activeHustles: 62 },
  { campus: 'Jimma Univ', users: 620, percentage: 13, activeHustles: 44 },
  { campus: 'Gondar Univ', users: 540, percentage: 11, activeHustles: 35 },
  { campus: 'Bahir Dar Univ', users: 582, percentage: 12, activeHustles: 41 },
]

export const RECENT_ACTIVITIES = [
  {
    id: 'act-1',
    type: 'verification',
    user: 'Yared Tadesse',
    campus: 'AAU 4k Main',
    action: 'Submitted ID verification (.edu email & Student Badge)',
    time: '8 minutes ago',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'pending',
  },
  {
    id: 'act-2',
    type: 'report',
    user: 'Bethlehem Alemu',
    campus: 'ASTU Adama',
    action: 'Reported listing "Calculus II Exam Solutions" for Academic Dishonesty',
    time: '24 minutes ago',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'high_priority',
  },
  {
    id: 'act-3',
    type: 'transaction',
    user: 'Dawit Solomon',
    campus: 'Hawassa Univ',
    action: 'Completed 2-hr Physics Tutor session with Abel K.',
    time: '45 minutes ago',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'completed',
  },
  {
    id: 'act-4',
    type: 'user',
    user: 'Selamawit Girma',
    campus: 'Jimma Univ',
    action: 'Registered as Peer Tutor for Organic Chemistry',
    time: '1 hour ago',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    status: 'new_user',
  },
  {
    id: 'act-5',
    type: 'verification',
    user: 'Kaleb Worku',
    campus: 'Gondar Univ',
    action: 'Approved verification for Seller Badge',
    time: '2 hours ago',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'approved',
  },
]

export const INITIAL_VERIFICATIONS = [
  {
    id: 'ver-101',
    userName: 'Yared Tadesse',
    userEmail: 'yared.t@aau.edu.et',
    campus: 'AAU 4k Main',
    major: 'Computer Engineering (Year 4)',
    type: 'Student & Tutor Badge',
    submittedAt: '2026-08-19 22:15',
    status: 'Pending',
    eduEmail: 'yared.t@aau.edu.et',
    studentIdNum: 'ETS-0842/14',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    idCardImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    proofDocument: 'Official Enrollment Certificate 2026.pdf',
    gpa: '3.82',
    notes: 'Submitted updated ID card showing valid 2026 registration stamp.',
  },
  {
    id: 'ver-102',
    userName: 'Hana Kebede',
    userEmail: 'hana.k@astu.edu.et',
    campus: 'ASTU Adama',
    major: 'Electrical & Electronics (Year 3)',
    type: 'Seller Verification',
    submittedAt: '2026-08-19 21:40',
    status: 'Pending',
    eduEmail: 'hana.k@astu.edu.et',
    studentIdNum: 'ASTU-1194/15',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    idCardImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    proofDocument: 'Dorm Registration & ID Scan.png',
    gpa: '3.65',
    notes: 'Wants seller badge for secondhand textbook store.',
  },
  {
    id: 'ver-103',
    userName: 'Michael Assefa',
    userEmail: 'michael.a@hu.edu.et',
    campus: 'Hawassa Univ',
    major: 'Civil Engineering (Year 5)',
    type: 'Tutor Badge',
    submittedAt: '2026-08-19 19:10',
    status: 'Pending',
    eduEmail: 'michael.a@hu.edu.et',
    studentIdNum: 'HU-0492/13',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    idCardImage: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=600&auto=format&fit=crop&q=80',
    proofDocument: 'Transcript_2026_Official.pdf',
    gpa: '3.91',
    notes: 'Applying as verified Tutor for Structural Dynamics.',
  },
  {
    id: 'ver-104',
    userName: 'Tigist Haile',
    userEmail: 'tigist.h@ju.edu.et',
    campus: 'Jimma Univ',
    major: 'Medicine & Health (Year 4)',
    type: 'Student Badge',
    submittedAt: '2026-08-19 16:30',
    status: 'Pending',
    eduEmail: 'tigist.h@ju.edu.et',
    studentIdNum: 'JU-0091/14',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    idCardImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    proofDocument: 'Jimma_Univ_Library_Card.jpg',
    gpa: '3.70',
    notes: 'ID card edge is slightly cropped in image.',
  },
  {
    id: 'ver-105',
    userName: 'Abel Tesfaye',
    userEmail: 'abel.t@bdu.edu.et',
    campus: 'Bahir Dar Univ',
    major: 'Economics (Year 2)',
    type: 'Seller Verification',
    submittedAt: '2026-08-19 14:05',
    status: 'Info Requested',
    eduEmail: 'abel.t@bdu.edu.et',
    studentIdNum: 'BDU-8821/16',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    idCardImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
    proofDocument: 'BDU_Student_Portal_Screenshot.png',
    gpa: '3.40',
    notes: 'Requested clearer photo of physical student card.',
  },
  {
    id: 'ver-106',
    userName: 'Rahel Desta',
    userEmail: 'rahel.d@aau.edu.et',
    campus: 'AAU 4k Main',
    major: 'Law (Year 3)',
    type: 'Student & Tutor Badge',
    submittedAt: '2026-08-18 11:20',
    status: 'Approved',
    eduEmail: 'rahel.d@aau.edu.et',
    studentIdNum: 'AAU-3321/15',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    idCardImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    proofDocument: 'AAU_Law_School_Enrollment.pdf',
    gpa: '3.88',
    notes: 'Approved by Admin Sarah on Aug 18.',
  },
]

export const INITIAL_REPORTS = [
  {
    id: 'rep-301',
    ticketNumber: 'TKT-9912',
    category: 'Academic Dishonesty',
    severity: 'High',
    status: 'Open',
    title: 'Selling leaked end-of-semester exam solutions',
    listingTitle: 'AAU Calc II Final Exam 2026 Answer Key',
    reportedUser: {
      name: 'Biniyam Fikru',
      id: 'usr-882',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      campus: 'AAU 4k Main',
      trustScore: 42,
      reportsCount: 3,
      status: 'Flagged',
    },
    reporter: {
      name: 'Bethlehem Alemu',
      id: 'usr-104',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      campus: 'AAU 4k Main',
      role: 'Student Representative',
    },
    assignee: 'Sarah Admin',
    createdAt: '2026-08-19 20:15',
    description:
      'User posted a listing claiming to provide exact 2026 final exam questions and answers for Calculus II. Violates honor code policy Section 4.2.',
    contextSnippet: '"Get 100% guarantee on Calc II exam tomorrow! Complete solved papers delivered via private chat after 200 ETB Telebirr transfer."',
    attachedEvidence: [
      'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&auto=format&fit=crop&q=80',
    ],
    internalNotes: [
      {
        id: 'n-1',
        author: 'Sarah Admin',
        time: '2026-08-19 20:30',
        text: 'Initial review confirms explicit offer for active exam material. Flagged seller account.',
      },
    ],
    auditTimeline: [
      { id: 'l-1', time: '2026-08-19 20:15', action: 'Report submitted by Bethlehem Alemu' },
      { id: 'l-2', time: '2026-08-19 20:30', action: 'Assigned to Sarah Admin' },
      { id: 'l-3', time: '2026-08-19 20:45', action: 'Listing visibility hidden automatically due to high severity' },
    ],
  },
  {
    id: 'rep-302',
    ticketNumber: 'TKT-9913',
    category: 'Scam / Non-Delivery',
    severity: 'High',
    status: 'Open',
    title: 'Paid 400 ETB for Lab Manual but received blank PDF',
    listingTitle: 'Organic Chemistry Lab Manual 2025 Annotated',
    reportedUser: {
      name: 'Elias Workneh',
      id: 'usr-671',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      campus: 'ASTU Adama',
      trustScore: 35,
      reportsCount: 2,
      status: 'Flagged',
    },
    reporter: {
      name: 'Tewodros Kassaye',
      id: 'usr-331',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      campus: 'ASTU Adama',
      role: 'Student',
    },
    assignee: 'Unassigned',
    createdAt: '2026-08-19 18:40',
    description:
      'Buyer sent 400 ETB via Chapa/Telebirr for annotated lab manual. Seller sent corrupted 0KB file and stopped replying.',
    contextSnippet: 'Payment TxID: CH-88419204. File attached by seller: chem_lab_notes.pdf (0 KB). Seller status: Away.',
    attachedEvidence: [
      'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    ],
    internalNotes: [],
    auditTimeline: [{ id: 'l-1', time: '2026-08-19 18:40', action: 'Report submitted by Tewodros Kassaye' }],
  },
  {
    id: 'rep-303',
    ticketNumber: 'TKT-9914',
    category: 'Spam / Harassment',
    severity: 'Medium',
    status: 'In Review',
    title: 'Repeated unwanted promo messages in tutor chat',
    listingTitle: 'Python Data Structures Tutor Session',
    reportedUser: {
      name: 'Solomon Berhanu',
      id: 'usr-554',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      campus: 'Jimma Univ',
      trustScore: 68,
      reportsCount: 1,
      status: 'Active',
    },
    reporter: {
      name: 'Meron Kidane',
      id: 'usr-219',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      campus: 'Jimma Univ',
      role: 'Student',
    },
    assignee: 'Kaleb Mod',
    createdAt: '2026-08-19 15:10',
    description: 'User spamming 15+ students with referral links to external betting/crypto platforms inside study chat rooms.',
    contextSnippet: '"Join this link to win ETB 5000 fast! Http://bit.ly/fake-campus-rewards"',
    attachedEvidence: [],
    internalNotes: [
      {
        id: 'n-1',
        author: 'Kaleb Mod',
        time: '2026-08-19 16:00',
        text: 'Issued temporary chat warning. Monitoring user messages for 24 hrs.',
      },
    ],
    auditTimeline: [
      { id: 'l-1', time: '2026-08-19 15:10', action: 'Report created' },
      { id: 'l-2', time: '2026-08-19 16:00', action: 'Warning issued by Kaleb Mod' },
    ],
  },
  {
    id: 'rep-304',
    ticketNumber: 'TKT-9915',
    category: 'Copyright / Counterfeit',
    severity: 'Low',
    status: 'Resolved',
    title: 'Listing PDF of copyrighted textbook without permission',
    listingTitle: 'Fundamentals of Electric Circuits 6th Edition PDF',
    reportedUser: {
      name: 'Robel Negash',
      id: 'usr-412',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      campus: 'Hawassa Univ',
      trustScore: 82,
      reportsCount: 0,
      status: 'Active',
    },
    reporter: {
      name: 'System Bot',
      id: 'sys-bot',
      avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
      campus: 'System',
      role: 'Automated Moderation',
    },
    assignee: 'Sarah Admin',
    createdAt: '2026-08-18 10:00',
    description: 'Automated scan detected copyrighted textbook PDF listing priced at 50 ETB.',
    contextSnippet: 'Title match: McGraw Hill Copyrighted Textbook',
    attachedEvidence: [],
    internalNotes: [
      {
        id: 'n-1',
        author: 'Sarah Admin',
        time: '2026-08-18 11:15',
        text: 'Removed listing and sent copyright policy notification to seller.',
      },
    ],
    auditTimeline: [
      { id: 'l-1', time: '2026-08-18 10:00', action: 'Flagged by System Bot' },
      { id: 'l-2', time: '2026-08-18 11:15', action: 'Listing removed by Sarah Admin' },
    ],
  },
]

export const INITIAL_USERS = [
  {
    id: 'usr-101',
    name: 'Yared Tadesse',
    email: 'yared.t@aau.edu.et',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    university: 'AAU 4k Main',
    role: 'Tutor',
    trustScore: 94,
    verificationStatus: 'Verified',
    status: 'Active',
    joinedDate: '2025-09-12',
    hustlesCompleted: 38,
    rating: 4.9,
    totalEarned: '$1,240',
    history: [
      { date: '2026-08-19', event: 'Completed Tutor Session: Calc II' },
      { date: '2026-08-10', event: 'Received 5-star review from Senait M.' },
      { date: '2025-09-12', event: 'Account Created & ID Verified' },
    ],
  },
  {
    id: 'usr-102',
    name: 'Bethlehem Alemu',
    email: 'bethlehem.a@aau.edu.et',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    university: 'AAU 4k Main',
    role: 'Student',
    trustScore: 88,
    verificationStatus: 'Verified',
    status: 'Active',
    joinedDate: '2025-10-01',
    hustlesCompleted: 14,
    rating: 4.8,
    totalEarned: '$210',
    history: [
      { date: '2026-08-19', event: 'Submitted report against user Biniyam F.' },
      { date: '2026-08-02', event: 'Purchased Python Study Guide' },
    ],
  },
  {
    id: 'usr-103',
    name: 'Biniyam Fikru',
    email: 'biniyam.f@aau.edu.et',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    university: 'AAU 4k Main',
    role: 'Seller',
    trustScore: 42,
    verificationStatus: 'Pending',
    status: 'Flagged',
    joinedDate: '2026-02-14',
    hustlesCompleted: 5,
    rating: 2.3,
    totalEarned: '$85',
    history: [
      { date: '2026-08-19', event: 'Flagged for Academic Dishonesty (Exam leak)' },
      { date: '2026-08-14', event: 'Reported by user for inaccurate listing description' },
    ],
  },
  {
    id: 'usr-104',
    name: 'Hana Kebede',
    email: 'hana.k@astu.edu.et',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    university: 'ASTU Adama',
    role: 'Seller',
    trustScore: 79,
    verificationStatus: 'Pending',
    status: 'Active',
    joinedDate: '2025-11-20',
    hustlesCompleted: 22,
    rating: 4.6,
    totalEarned: '$480',
    history: [
      { date: '2026-08-19', event: 'Requested Seller Badge Verification' },
      { date: '2026-07-28', event: 'Sold Engineering Graphics Set' },
    ],
  },
  {
    id: 'usr-105',
    name: 'Michael Assefa',
    email: 'michael.a@hu.edu.et',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    university: 'Hawassa Univ',
    role: 'Tutor',
    trustScore: 96,
    verificationStatus: 'Verified',
    status: 'Active',
    joinedDate: '2025-08-04',
    hustlesCompleted: 52,
    rating: 5.0,
    totalEarned: '$2,150',
    history: [
      { date: '2026-08-19', event: 'Applied for Lead Tutor Certification' },
      { date: '2026-08-15', event: 'Tutored 6 students in Structural Dynamics' },
    ],
  },
  {
    id: 'usr-106',
    name: 'Sarah Admin',
    email: 'sarah.admin@campushustle.edu.et',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    university: 'CampusHustle HQ',
    role: 'Admin',
    trustScore: 100,
    verificationStatus: 'Verified',
    status: 'Active',
    joinedDate: '2025-01-01',
    hustlesCompleted: 0,
    rating: 5.0,
    totalEarned: '$0',
    history: [
      { date: '2026-08-19', event: 'Reviewed 12 verification queue items' },
      { date: '2026-08-18', event: 'Resolved TKT-9915 copyright report' },
    ],
  },
  {
    id: 'usr-107',
    name: 'Elias Workneh',
    email: 'elias.w@astu.edu.et',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    university: 'ASTU Adama',
    role: 'Seller',
    trustScore: 35,
    verificationStatus: 'Unverified',
    status: 'Suspended',
    joinedDate: '2026-05-10',
    hustlesCompleted: 3,
    rating: 1.8,
    totalEarned: '$40',
    history: [
      { date: '2026-08-19', event: 'Temporary 7-day suspension for non-delivery scam' },
      { date: '2026-08-19', event: 'Received High Severity Report TKT-9913' },
    ],
  },
  {
    id: 'usr-108',
    name: 'Tigist Haile',
    email: 'tigist.h@ju.edu.et',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    university: 'Jimma Univ',
    role: 'Student',
    trustScore: 85,
    verificationStatus: 'Pending',
    status: 'Active',
    joinedDate: '2026-01-18',
    hustlesCompleted: 8,
    rating: 4.7,
    totalEarned: '$120',
    history: [
      { date: '2026-08-19', event: 'Submitted ID Badge verification' },
    ],
  },
]
